-- MySQL Script generated by MySQL Workbench
-- 02/15/17 15:30:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema alice
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `alice` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
SET NAMES "UTF8";
USE `alice` ;

-- -----------------------------------------------------
-- Table `alice`.`AGENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alice`.`agent` (
  `idAgent` TINYINT(2) UNIQUE NOT NULL,
  `nom` VARCHAR(20),
  `prenom` VARCHAR(20),
  `login` VARCHAR(20),
  `mdp` VARCHAR(20),
  `statut` CHAR(1),
  `idBiblio` CHAR(1),
  PRIMARY KEY (`idAgent`))
ENGINE = InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `alice`.`FERIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alice`.`ferie` (
  `idFerie` TINYINT(2) UNIQUE NOT NULL,
  `nomFerie` VARCHAR(20) NOT NULL,
  `dateDebFerie` DATE NOT NULL,
  `dateFinFerie` DATE )
ENGINE = InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `alice`.`GROUPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alice`.`groupe` (
  `idGroupe` TINYINT(1) UNIQUE NOT NULL,
  `libGroupe` VARCHAR(30) NOT NULL,
  `coulGroupe` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idGroupe`))
ENGINE = InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `alice`.`HORAIRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alice`.`horaire` (
  `idHoraire` TINYINT(1) UNIQUE NOT NULL,
  `libHoraire` TIME NOT NULL,
  PRIMARY KEY (`idHoraire`))
ENGINE = InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `alice`.`POSTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alice`.`poste` (
  `idPoste` TINYINT(2) UNIQUE NOT NULL,
  `libPoste` VARCHAR(20) NOT NULL,
  `typePoste` TINYINT(1) NOT NULL,
  `idGroupe` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idPoste`),
  INDEX `idGroupe_idx` (`idGroupe` ASC),
  CONSTRAINT `idGroupe`
    FOREIGN KEY (`idGroupe`)
    REFERENCES `alice`.`GROUPE` (`idGroupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `alice`.`PLANSTD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alice`.`planstd` (
  `idAgent` TINYINT(2) NOT NULL,
  `idJour` TINYINT(1) NOT NULL,
  `horaireDeb` TINYINT(1) NOT NULL,
  `horaireFin` TINYINT(1) NOT NULL,
  `idPoste` TINYINT(2),
  PRIMARY KEY (`idAgent`, `idJour`, `horaireDeb`, `horaireFin`),
  INDEX `heureDeb_idx` (`horaireDeb` ASC),
  INDEX `heureFin_idx` (`horaireFin` ASC),
  INDEX `idPoste_idx` (`idPoste` ASC),
  CONSTRAINT `idAgentStd`
    FOREIGN KEY (`idAgent`)
    REFERENCES `alice`.`AGENT` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `heureDebStd`
    FOREIGN KEY (`horaireDeb`)
    REFERENCES `alice`.`HORAIRE` (`idHoraire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `heureFinStd`
    FOREIGN KEY (`horaireFin`)
    REFERENCES `alice`.`HORAIRE` (`idHoraire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPosteStd`
    FOREIGN KEY (`idPoste`)
    REFERENCES `alice`.`POSTE` (`idPoste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `alice`.`PLANREEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alice`.`planreel` (
  `idAgent` TINYINT(2) NOT NULL,
  `dateReel` DATE NOT NULL,
  `horaireDeb` TINYINT(1) NOT NULL,
  `horaireFin` TINYINT(1) NOT NULL,
  `idPoste` TINYINT(2) NOT NULL,
  PRIMARY KEY (`idAgent`, `dateReel`, `horaireDeb`, `horaireFin`),
  INDEX `heureDeb_idx` (`horaireDeb` ASC),
  INDEX `heureFin_idx` (`horaireFin` ASC),
  INDEX `idPoste_idx` (`idPoste` ASC),
  CONSTRAINT `idAgentReel`
    FOREIGN KEY (`idAgent`)
    REFERENCES `alice`.`AGENT` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `heureDebReel`
    FOREIGN KEY (`horaireDeb`)
    REFERENCES `alice`.`HORAIRE` (`idHoraire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `heureFinReel`
    FOREIGN KEY (`horaireFin`)
    REFERENCES `alice`.`HORAIRE` (`idHoraire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPosteReel`
    FOREIGN KEY (`idPoste`)
    REFERENCES `alice`.`POSTE` (`idPoste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `alice`.`VACANCES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alice`.`vacances` (
  `idVac` TINYINT(1) UNIQUE NOT NULL,
  `nomVac` VARCHAR(20) NOT NULL,
  `dateDebVac` DATE NOT NULL,
  `dateFinVac` DATE NOT NULL)
ENGINE = InnoDB DEFAULT CHARSET=latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
